// <auto-generated />
using System;
using Consolidado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consolidado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20260627145331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consolidado.Domain.EventoProcessado", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em_utc");

                    b.HasKey("EventId")
                        .HasName("pk_eventos_processados");

                    b.ToTable("eventos_processados", (string)null);
                });

            modelBuilder.Entity("Consolidado.Domain.SaldoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<string>("ComercianteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comerciante_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Fechado")
                        .HasColumnType("boolean")
                        .HasColumnName("fechado");

                    b.Property<int>("QuantidadeLancamentos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_lancamentos");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_debitos");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_saldos_diarios");

                    b.HasIndex("ComercianteId", "Data")
                        .IsUnique()
                        .HasDatabaseName("ix_saldos_diarios_comerciante_id_data");

                    b.ToTable("saldos_diarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
